version: '3.3'
services:
  db:
    image: postgres:13.4
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: simarglwp/fdgrm
    container_name: backend
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: simarglwp/fdgrm_frnt
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - nginx
  nginx:
    image: nginx:1.20.1
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
